### ISSUE TITLE
wrong number of arguments for 'hset' command

### ISSUE THREAD

**Issue by j178** [redis-collections/redis-collections#141]
Hi, thanks for this project, it's really helpful!

I encountered this problem while using a `data=<dict>` to populate initial data:  `wrong number of arguments for 'hset' command`

My code:
```py
redis = Redis.from_url(constant.REDIS_URI)
d = Dict(data={"a:": 1, "b": 1}, redis=redis)
```

- redis-collections: 0.9.0
- reids: 3.5.3
- Python: 3.6.8
- Redis server: 3.2.12

Here is the full traceback:
<details>
  <summary>Traceback (most recent call last):</summary>

```
Traceback (most recent call last):
  File "/Users/didi/code/oneoff/dchat/dchat-robots/.venv/lib/python3.6/site-packages/redis/client.py", line 3911, in _execute_transaction
    response = self.parse_response(connection, '_')
  File "/Users/didi/code/oneoff/dchat/dchat-robots/.venv/lib/python3.6/site-packages/redis/client.py", line 3978, in parse_response
    self, connection, command_name, **options)
  File "/Users/didi/code/oneoff/dchat/dchat-robots/.venv/lib/python3.6/site-packages/redis/client.py", line 915, in parse_response
    response = connection.read_response()
  File "/Users/didi/code/oneoff/dchat/dchat-robots/.venv/lib/python3.6/site-packages/redis/connection.py", line 756, in read_response
    raise response
redis.exceptions.ExecAbortError: Transaction discarded because of previous errors.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/didi/code/oneoff/dchat/dchat-robots/mock.py", line 82, in <module>
    test_redis()
  File "/Users/didi/code/oneoff/dchat/dchat-robots/mock.py", line 57, in test_redis
    d = Dict(data={"a:": 1, "b": 1}, redis=redis)
  File "/Users/didi/code/oneoff/dchat/dchat-robots/.venv/lib/python3.6/site-packages/redis_collections/dicts.py", line 93, in __init__
    self.update(data)
  File "/Users/didi/code/oneoff/dchat/dchat-robots/.venv/lib/python3.6/site-packages/redis_collections/dicts.py", line 348, in update
    self._update_helper(other)
  File "/Users/didi/code/oneoff/dchat/dchat-robots/.venv/lib/python3.6/site-packages/redis_collections/dicts.py", line 332, in _update_helper
    self._transaction(_update_helper_trans)
  File "/Users/didi/code/oneoff/dchat/dchat-robots/.venv/lib/python3.6/site-packages/redis_collections/base.py", line 222, in _transaction
    self.redis.transaction(trans, self.key, *extra_keys)
  File "/Users/didi/code/oneoff/dchat/dchat-robots/.venv/lib/python3.6/site-packages/redis/client.py", line 805, in transaction
    exec_value = pipe.execute()
  File "/Users/didi/code/oneoff/dchat/dchat-robots/.venv/lib/python3.6/site-packages/redis/client.py", line 4019, in execute
    return execute(conn, stack, raise_on_error)
  File "/Users/didi/code/oneoff/dchat/dchat-robots/.venv/lib/python3.6/site-packages/redis/client.py", line 3914, in _execute_transaction
    raise errors[0][1]
  File "/Users/didi/code/oneoff/dchat/dchat-robots/.venv/lib/python3.6/site-packages/redis/client.py", line 3904, in _execute_transaction
    self.parse_response(connection, '_')
  File "/Users/didi/code/oneoff/dchat/dchat-robots/.venv/lib/python3.6/site-packages/redis/client.py", line 3978, in parse_response
    self, connection, command_name, **options)
  File "/Users/didi/code/oneoff/dchat/dchat-robots/.venv/lib/python3.6/site-packages/redis/client.py", line 915, in parse_response
    response = connection.read_response()
  File "/Users/didi/code/oneoff/dchat/dchat-robots/.venv/lib/python3.6/site-packages/redis/connection.py", line 756, in read_response
    raise response
redis.exceptions.ResponseError: Command # 1 (HSET 81d1b5c8bf2e46c2899742c0e23616d3 ���b�. ��K. ���a:�. ��K.) of pipeline caused error: wrong number of arguments for 'hset' command
```
</details>

**Comment by j178** [comment]
I get it, the variadic form of `hset` is only allowed since redis 4.0:

> As of Redis 4.0.0, HSET is variadic and allows for multiple field/value pairs.

maybe this `_hmset` needs some tweaks:
https://github.com/redis-collections/redis-collections/blob/437f1c4bccd6b4e7f753732a27997b51d0bb51d6/redis_collections/base.py#L154-L159

**Comment by bbayles** [comment]
Thanks for the report. I assumed that the `redis` library would handle this, but after reading I see that it doesn't.

My options here aren't very good:
1. Get rid of the `hset` branch and always use `hmset` - this will cause a [DeprecationWarning](https://github.com/andymccurdy/redis-py/blob/1a41cfd95a53a95b078084d8627be6b6fba3bb71/redis/client.py#L3169).
2. Try `hset` and fall back to `hmset` if the command fails - this would mean worse performance for at least the initial `HMSET`
3. Drop support for Redis versions below 4.0 - this goes against [the docs](https://github.com/redis-collections/redis-collections/blame/6acae6f4c5a63210032eb8222f68ea8192e17886/docs/development.rst#L35-L37), which say that `redis-collections` supports whatever the current LTS Ubuntu releases support.

I'm inclined to do a patch release with (2) and then implement (3), as Ubuntu 16.04 with Redis 3.0.6 goes EOL next month. What do you think?

**Comment by j178** [comment]
That's nice, thank you for the quick response!
